# Generated by Django 3.0.3 on 2020-02-16 11:03

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualizar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('actualizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='distritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('provincia_id', models.IntegerField()),
                ('actualizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('departamento_id', models.IntegerField()),
                ('actualizado', models.BooleanField(default=False)),
                ('departamento_provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.departamento', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dni', models.CharField(max_length=250, verbose_name='Nº de DNI ')),
                ('nombre_persona', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombres ')),
                ('apellido_paterno', models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellido Paterno ')),
                ('apellido_materno', models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellido Materno ')),
                ('sexo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sexo ')),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=250, null=True, verbose_name='Fecha de Nacimiento')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen de la Persona')),
                ('departamento_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.departamento')),
                ('distrito_persona', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='provincia_persona', chained_model_field='provincia_distrito', on_delete=django.db.models.deletion.CASCADE, to='personal.distritos')),
                ('provincia_persona', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='departamento_persona', chained_model_field='departamento_provincia', on_delete=django.db.models.deletion.CASCADE, to='personal.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='distritos',
            name='provincia_distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.provincia', verbose_name='Provincia'),
        ),
    ]
