# Generated by Django 3.0.3 on 2020-02-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_todosfalse'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='confirmacion_correo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='confirmacion_wsp',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Numerode telefono(Opcional)'),
        ),
    ]
