# Generated by Django 3.0.3 on 2020-02-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envio_Gmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asunto', models.CharField(max_length=250, verbose_name='Asunto del Mensaje ')),
                ('Cuerpo', models.TextField(verbose_name='Cuerpo del Mensaje ')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen (opcional)')),
            ],
        ),
        migrations.CreateModel(
            name='Envio_Whatsapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asunto', models.CharField(max_length=250, verbose_name='Asunto del Mensaje ')),
                ('Cuerpo', models.TextField(verbose_name='Cuerpo del Mensaje ')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen (opcional)')),
            ],
        ),
    ]
