# Generated by Django 3.0.3 on 2020-02-18 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Envio_Mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio_gmail',
            options={'verbose_name': 'Enviar Mensajes Gmail'},
        ),
        migrations.AlterModelOptions(
            name='envio_whatsapp',
            options={'verbose_name': 'Enviar Mensajes Whatsapp'},
        ),
    ]
